### ISSUE TITLE
Tracking: zk-friendliness in RGB

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb#264]
- [x] Remove bulletproofs support: https://github.com/RGB-WG/rgb/issues/263
- [x] Reduce AluVM instruction set to zk-friendly operations only: https://github.com/AluVM/rust-aluvm/pull/128
- [ ] Make single-use seals to commit to hash function
- [ ] Check support for additional VM in schema and scripts (for the future zkAluVM or other zkVM)
- [ ] Commit just to one single-use seal closing method (per blockchain) in the contract genesis

Related discussion: https://github.com/orgs/RGB-WG/discussions/265
